title: Monkey's Namespace
source: .
destination: ./_site
layout: ./_layouts
categories: blog,movie,travel
tags: tech,movie,travel,photo,book,
email: xiaochan.xia@qq.com
baseUrl: ""


#Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
